server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  # 连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yyd-yun/springcloud-config.git # http不是git
          username: yyd-yun
          password: 2455899745yyd
          #search-paths: config
          force-pull: true
#Eureka的配置  配置服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance-id: springcloud-config-server-3344 #修改Eureka默认名称 描述信息
    prefer-ip-address: false # false隐藏IP ture显示IP